sylius_shop_product_index:
  path: /{slug}
  methods: [GET]
  defaults:
    _controller: sylius.controller.product:indexAction
    _sylius:
      template: "@SyliusShop/Product/index.html.twig"
      grid: sylius_shop_product
  requirements:
    slug: .+
  condition: "context.checkTaxonSlug(request.getPathInfo())"
